name: Generate docu-lite outline

on:
  push:
    paths:
      - '**.py'
      
  workflow_dispatch:
      
jobs:
  outline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true  # ← this is critical
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install docu-lite
        run: |
          python -m pip install docu-lite 

      - name: Run docu-lite
        run: |
          cd docs
          docu-lite
          docu-lite --config docu-lite-docmode.ini
